export const mapFields = [
    { value: "numIncarcerated",
      label: "Number Serving Sentence in Facility Within County" },
    { value: "numIncarceratedMale",
      label: "Number Males Serving Sentence in Facility Within County" },
    { value: "numIncarceratedFemale",
      label: "Number Femalese Serving Sentence in Facility Within County" },
    { value: "numCrimeCommitted",
      label: "Number Incarcerated" },
    { value: "numCrimeCommittedMale",
      label: "Number Males Incarcerated" },
    { value: "numCrimeCommittedFemale",
      label: "Number Females Incarcerated" },
    { value: "population",
      label: "County Population" },
    { value: "populationMale",
      label: "County Male Population" },
    { value: "populationFemale",
      label: "County Female Population" },
    { value: "incarcerationRate",
      label: "Incarceration Rate" },
    { value: "incarcerationRateMale",
      label: "Incarceration Rate Male" },
    { value: "incarcerationRateFemale",
      label: "Incarceration Rate Female" },
    { value: "countyHispanic",
      label: "County Hispanic Population" },
    { value: "countyHispanicPct",
      label: "County Hispanic Percent" },
    { value: "countyNHWhite",
      label: "County NH-White Population" },
    { value: "countyNYWhitePct",
      label: "County NH-White Percent" },
    { value: "countyNHBlackPct",
      label: "County NH-Black Percent" },
    { value: "countyNHOther",
      label: "County NH-Other Population" },
    { value: "countyNHOtherPct",
      label: "County NH-Other Percent" },
    { value: "prisonHispanic",
      label: "Prison Hispanic Population" },
    { value: "prisonHispanicPct",
      label: "Prison Hispanic Percent" },
    { value: "prisonNHWhite",
      label: "Prison NHWhite Population" },
    { value: "prisonNHWhitePct",
      label: "Prison NHWhite Percent" },
    { value: "prisonNHBlack",
      label: "Prison NHBlack Population" },
    { value: "prisonNHBlackPct",
      label: "Prison NHBlack Percent" },
    { value: "prisonNHOther",
      label: "Prison NH Other Population" },
    { value: "prisonNHOtherPct",
      label: "Prison NH Other Percent" },
    { value: "incarcerationRateHispanic",
      label: "Incarceration Rate Hispanic" },
    { value: "incarcerationRateNHWhite",
      label: "Incarceration Rate NHWhite" },
    { value: "incarcerationRateNHBlack",
      label: "Incarceration Rate NHBlack" },
    { value: "incarcerationRateNHOther",
      label: "Incarceration Rate NHOther" },
    { value: "pctUnemployed",
      label: "Percent Unemployed Over 16" },
    { value: "pctFoodStamps",
      label: "Percent Used Food Stamps in Last 12 months" },
    { value: "pctPovertyLine",
      label: "Percent Below Poverty Line" },
    { value: "pctHighSchool",
      label: "Percent Over 25 High School Graduate" },
    { value: "pctBachelors",
      label: "Percent Over 25 Bachelors or Higher" },
    ]
